import type { Comprobante, ComprobanteVenta, ComprobantePago, ItemComprobante } from '@/types/comprobante.types'

const itemsPollos: ItemComprobante[] = [
  { nombre: 'Pollo Entero', cantidad: 2, precio_unitario: 8.5, subtotal: 17 },
  { nombre: 'Pollo Pierna', cantidad: 4, precio_unitario: 3, subtotal: 12 },
  { nombre: 'Alas', cantidad: 3, precio_unitario: 4, subtotal: 12 },
]

const itemsPolloParcial: ItemComprobante[] = [
  { nombre: 'Pollo Entero', cantidad: 1, precio_unitario: 8.5, subtotal: 8.5 },
  { nombre: 'Menudencia', cantidad: 2, precio_unitario: 2, subtotal: 4 },
]

export const COMPROBANTES_MOCK: Comprobante[] = [
  {
    id: 'comp-001',
    numero: '001-00001',
    tipo: 'venta',
    fecha: new Date('2024-01-15T10:30:00'),
    hora: '10:30 AM',
    estado: 'activo',
    negocio_nombre: 'Sam José Avícola',
    negocio_ruc: '20000000000',
    negocio_direccion: 'Av. Principal 123, Arequipa',
    negocio_telefono: '+51 916 794 870',
    cliente_nombre: 'María López',
    cliente_documento: '45234567',
    items: [
      { nombre: 'Pollo Entero', cantidad: 2, precio_unitario: 8.5, subtotal: 17 },
      { nombre: 'Pollo Pierna', cantidad: 4, precio_unitario: 3, subtotal: 12 },
      { nombre: 'Alas', cantidad: 3, precio_unitario: 4, subtotal: 12 },
    ],
    subtotal: 34.75,
    descuento: 0,
    igv: 6.25,
    total: 41,
    metodo_pago: 'efectivo',
    efectivo: 50,
    vuelto: 9,
    vendedor_nombre: 'Juan Pérez',
  } as ComprobanteVenta,
  {
    id: 'comp-002',
    numero: '001-00002',
    tipo: 'venta',
    fecha: new Date('2024-01-15T14:20:00'),
    hora: '02:20 PM',
    estado: 'activo',
    negocio_nombre: 'Sam José Avícola',
    negocio_ruc: '20000000000',
    negocio_direccion: 'Av. Principal 123, Arequipa',
    negocio_telefono: '+51 916 794 870',
    cliente_nombre: 'Carlos Mendoza',
    items: [
      { nombre: 'Pollo Entero', cantidad: 1, precio_unitario: 8.5, subtotal: 8.5 },
      { nombre: 'Menudencia', cantidad: 2, precio_unitario: 2, subtotal: 4 },
    ],
    subtotal: 10.59,
    descuento: 0,
    igv: 1.91,
    total: 12.5,
    metodo_pago: 'yape',
    vendedor_nombre: 'Juan Pérez',
  } as ComprobanteVenta,
  {
    id: 'comp-pago-001',
    numero: '001-00003',
    tipo: 'pago_cobranza',
    fecha: new Date('2024-01-20T16:00:00'),
    hora: '04:00 PM',
    estado: 'activo',
    negocio_nombre: 'Sam José Avícola',
    negocio_ruc: '20000000000',
    negocio_direccion: 'Av. Principal 123, Arequipa',
    negocio_telefono: '+51 916 794 870',
    cliente_id: 'cli-001',
    cliente_nombre: 'Restaurante El Gallo',
    cliente_documento: '20456789012',
    deuda_total_original: 300,
    total_pagado_anterior: 100,
    deuda_actual: 200,
    monto_pagado: 100,
    nueva_deuda: 100,
    metodo_pago: 'transferencia',
    observaciones: 'Pago a cuenta',
    ventas: [
      {
        ticket: '001-00001',
        fecha: new Date('2024-01-10'),
        items: itemsPollos,
        subtotal: 34.75,
        descuento: 0,
        igv: 6.25,
        total: 41,
        monto_pagado_anterior: 41,
        monto_pagado_ahora: 0,
        nuevo_saldo: 0,
        estado: 'pagado',
      },
      {
        ticket: '001-00002',
        fecha: new Date('2024-01-12'),
        items: itemsPolloParcial,
        subtotal: 10.59,
        descuento: 0,
        igv: 1.91,
        total: 12.5,
        monto_pagado_anterior: 0,
        monto_pagado_ahora: 50,
        nuevo_saldo: 0,
        estado: 'pagado',
      },
      {
        ticket: '001-00003',
        fecha: new Date('2024-01-15'),
        items: [
          { nombre: 'Pollo Entero', cantidad: 10, precio_unitario: 8.5, subtotal: 85 },
          { nombre: 'Pollo Mitades', cantidad: 10, precio_unitario: 5, subtotal: 50 },
          { nombre: 'Menudencia', cantidad: 5, precio_unitario: 2, subtotal: 10 },
        ],
        subtotal: 122.88,
        descuento: 10,
        igv: 20.32,
        total: 145,
        monto_pagado_anterior: 59,
        monto_pagado_ahora: 50,
        nuevo_saldo: 36,
        estado: 'parcial',
      },
    ],
    ventas_pagadas_count: 2,
    ventas_parciales_count: 1,
    usuario_nombre: 'Juan Pérez',
    total: 100,
  } as ComprobantePago,
  // === PAGO DE JUAN PÉREZ (CLIENTE C3) - Solo pago, no comprobante de venta porque no pagó en el momento
  {
    id: 'comp-jp-pago-001',
    numero: '001-00103',
    tipo: 'pago_cobranza',
    fecha: new Date('2026-04-19T11:00:00'),
    hora: '11:00 AM',
    estado: 'activo',
    negocio_nombre: 'Sam José Avícola',
    negocio_ruc: '20000000000',
    negocio_direccion: 'Av. Principal 123, Arequipa',
    negocio_telefono: '+51 916 794 870',
    cliente_id: 'c3',
    cliente_nombre: 'Juan Pérez',
    cliente_documento: '87654321',
    cliente_tipo: 'especial',
    deuda_total_original: 145.58,
    total_ventas_sin_descuento: 129.87,
    total_pagado_anterior: 0,
    deuda_actual: 145.58,
    monto_pagado: 72.44,
    nueva_deuda: 73.14,
    metodo_pago: 'transferencia',
    observaciones: 'Pago parcial de cuenta',
    ventas: [
      {
        ticket: 'SAM-00100',
        fecha: new Date('2026-04-15'),
        items: [
          { nombre: 'Pollo Entero', cantidad: 5, precio_unitario: 8.5, subtotal: 42.5 },
          { nombre: 'Alas', cantidad: 3, precio_unitario: 4, subtotal: 12 },
          { nombre: 'Pechuga', cantidad: 2, precio_unitario: 12, subtotal: 24 },
        ],
        subtotal: 64.62,
        descuento: 3.23,
        igv: 11.05,
        total: 72.44,
        monto_pagado_anterior: 0,
        monto_pagado_ahora: 72.44,
        nuevo_saldo: 0,
        estado: 'pagado',
      },
      {
        ticket: 'SAM-00101',
        fecha: new Date('2026-04-18'),
        items: [
          { nombre: 'Pollo Entero', cantidad: 8, precio_unitario: 8.5, subtotal: 68 },
          { nombre: 'Menudencia', cantidad: 5, precio_unitario: 2, subtotal: 10 },
        ],
        subtotal: 65.25,
        descuento: 3.26,
        igv: 11.15,
        total: 73.14,
        monto_pagado_anterior: 0,
        monto_pagado_ahora: 0,
        nuevo_saldo: 73.14,
        estado: 'parcial',
      },
    ],
    ventas_pagadas_count: 1,
    ventas_parciales_count: 1,
    usuario_nombre: 'Juan Pérez',
    total: 72.44,
  } as ComprobantePago,
  // === EJEMPLO: PAGO PARCIAL DE JUAN PÉREZ ===
  // Cuando se hizo este pago, la venta SAM-00150 tenía total S/ 91.31
  // Juan pagó S/ 45.00, quedando pendiente S/ 46.31
  {
    id: 'comp-pago-parcial-001',
    numero: '001-00150',
    tipo: 'pago_cobranza',
    fecha: new Date('2026-04-21T10:00:00'),
    hora: '10:00 AM',
    estado: 'activo',
    negocio_nombre: 'Sam José Avícola',
    negocio_ruc: '20000000000',
    negocio_direccion: 'Av. Principal 123, Arequipa',
    negocio_telefono: '+51 916 794 870',
    cliente_id: 'c3',
    cliente_nombre: 'Juan Pérez',
    cliente_documento: '87654321',
    cliente_tipo: 'especial',
    deuda_total_original: 91.31,
    total_ventas_sin_descuento: 97.00,
    total_pagado_anterior: 0,
    deuda_actual: 91.31,
    monto_pagado: 45.00,
    nueva_deuda: 46.31,
    metodo_pago: 'yape',
    observaciones: 'Pago parcial por atención',
    ventas: [
      {
        ticket: 'SAM-00150',
        fecha: new Date('2026-04-20'),
        items: [
          { nombre: 'Pollo Entero', cantidad: 10, precio_unitario: 7.80, subtotal: 78.00 },
          { nombre: 'Alas', cantidad: 5, precio_unitario: 3.80, subtotal: 19.00 },
        ],
        subtotal: 81.45,
        descuento: 4.07,
        igv: 13.93,
        total: 91.31,
        monto_pagado_anterior: 0,
        monto_pagado_ahora: 45.00,
        nuevo_saldo: 46.31,
        estado: 'parcial',
      },
    ],
    ventas_pagadas_count: 0,
    ventas_parciales_count: 1,
    usuario_nombre: 'Caja',
    total: 45.00,
  } as ComprobantePago,
]