import type { MovimientoInventario, ConteoInventario } from '@/types/inventario.types'

export const MOVIMIENTOS_MOCK: MovimientoInventario[] = [
  {
    id: 'mov-001',
    producto_id: '1',
    producto_nombre: 'Pollo Entero Grado A',
    tipo: 'entrada',
    cantidad: 50,
    motivo: 'compra',
    notas: 'Pedido al proveedor Avicola Los Andes',
    fecha: new Date('2026-03-18T08:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'compra',
    documento_id: 'comp1',
  },
  {
    id: 'mov-002',
    producto_id: '1',
    producto_nombre: 'Pollo Entero Grado A',
    tipo: 'salida',
    cantidad: 10,
    motivo: 'venta',
    fecha: new Date('2026-03-19T09:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'venta',
    documento_id: 'v1',
  },
  {
    id: 'mov-003',
    producto_id: '2',
    producto_nombre: 'Cartón Huevos x30',
    tipo: 'entrada',
    cantidad: 20,
    motivo: 'compra',
    notas: 'Proveedor Granja Santa María',
    fecha: new Date('2026-03-17T10:15:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'compra',
    documento_id: 'comp2',
  },
  {
    id: 'mov-004',
    producto_id: '2',
    producto_nombre: 'Cartón Huevos x30',
    tipo: 'salida',
    cantidad: 2,
    motivo: 'venta',
    fecha: new Date('2026-03-19T10:15:00'),
    usuario_id: 'usr_002',
    documento_tipo: 'venta',
    documento_id: 'v2',
  },
  {
    id: 'mov-005',
    producto_id: '4',
    producto_nombre: 'Muslos de Pollo',
    tipo: 'salida',
    cantidad: 3,
    motivo: 'venta',
    fecha: new Date('2026-03-19T11:00:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'venta',
    documento_id: 'v3',
  },
  {
    id: 'mov-006',
    producto_id: '4',
    producto_nombre: 'Muslos de Pollo',
    tipo: 'salida',
    cantidad: 1,
    motivo: 'merma',
    notas: 'Producto en mal estado',
    fecha: new Date('2026-04-06T08:00:00'),
    usuario_id: 'usr_002',
  },
  {
    id: 'mov-007',
    producto_id: '1',
    producto_nombre: 'Pollo Entero Grado A',
    tipo: 'salida',
    cantidad: 15,
    motivo: 'venta',
    fecha: new Date('2026-03-19T14:30:00'),
    usuario_id: 'usr_002',
    documento_tipo: 'venta',
    documento_id: 'v4',
  },
  {
    id: 'mov-008',
    producto_id: '1',
    producto_nombre: 'Pollo Entero Grado A',
    tipo: 'salida',
    cantidad: 2.5,
    motivo: 'merma',
    notas: 'Producto vencido por temperatura',
    fecha: new Date('2026-04-04T09:00:00'),
    usuario_id: 'usr_001',
  },
  {
    id: 'mov-009',
    producto_id: '1',
    producto_nombre: 'Pollo Entero Grado A',
    tipo: 'entrada',
    cantidad: 5,
    motivo: 'ajuste',
    notas: 'Corrección de inventario - error de conteo anterior',
    fecha: new Date('2026-04-06T10:00:00'),
    usuario_id: 'usr_001',
  },
  {
    id: 'mov-010',
    producto_id: '2',
    producto_nombre: 'Cartón Huevos x30',
    tipo: 'salida',
    cantidad: 1,
    motivo: 'merma',
    notas: 'Huevos rotos durante transporte',
    fecha: new Date('2026-04-04T07:30:00'),
    usuario_id: 'usr_001',
  },
  {
    id: 'mov-011',
    producto_id: '2',
    producto_nombre: 'Cartón Huevos x30',
    tipo: 'salida',
    cantidad: 1,
    motivo: 'regalo',
    notas: 'Caja de muestra para nuevo cliente',
    fecha: new Date('2026-04-05T13:20:00'),
    usuario_id: 'usr_001',
  },
  {
    id: 'mov-012',
    producto_id: '3',
    producto_nombre: 'Pechuga Especial',
    tipo: 'entrada',
    cantidad: 20,
    motivo: 'compra',
    notas: 'Proveedor Avicola Los Andes',
    fecha: new Date('2026-03-18T08:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'compra',
    documento_id: 'comp1',
  },
  {
    id: 'mov-013',
    producto_id: '3',
    producto_nombre: 'Pechuga Especial',
    tipo: 'salida',
    cantidad: 5,
    motivo: 'venta',
    fecha: new Date('2026-03-19T09:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'venta',
    documento_id: 'v1',
  },
  // Movimientos generados por conteos de inventario
  {
    id: 'mov-014',
    producto_id: '1',
    producto_nombre: 'Pollo Entero Grado A',
    tipo: 'salida',
    cantidad: 2,
    motivo: 'merma',
    notas: 'Conteo INV-0001: diferencia no justificada',
    fecha: new Date('2026-04-10T10:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'conteo',
    documento_id: 'INV-0001',
  },
  {
    id: 'mov-015',
    producto_id: '2',
    producto_nombre: 'Cartón Huevos x30',
    tipo: 'entrada',
    cantidad: 2,
    motivo: 'correccion',
    notas: 'Conteo INV-0001: corrección de inventario',
    fecha: new Date('2026-04-10T10:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'conteo',
    documento_id: 'INV-0001',
  },
  {
    id: 'mov-016',
    producto_id: '4',
    producto_nombre: 'Muslos de Pollo',
    tipo: 'salida',
    cantidad: 1,
    motivo: 'merma',
    notas: 'Conteo INV-0001: diferencia no justificada',
    fecha: new Date('2026-04-10T10:30:00'),
    usuario_id: 'usr_001',
    documento_tipo: 'conteo',
    documento_id: 'INV-0001',
  },
  {
    id: 'mov-017',
    producto_id: '2',
    producto_nombre: 'Cartón Huevos x30',
    tipo: 'salida',
    cantidad: 1,
    motivo: 'merma',
    notas: 'Conteo INV-0002: diferencia no justificada',
    fecha: new Date('2026-04-12T15:00:00'),
    usuario_id: 'usr_002',
    documento_tipo: 'conteo',
    documento_id: 'INV-0002',
  },
]

export const CONTEOS_MOCK: ConteoInventario[] = [
  {
    id: 'conteo-001',
    numero: 'INV-0001',
    usuario_id: 'usr_001',
    usuario_nombre: 'Admin User',
    items: [
      { producto_id: '1', producto_nombre: 'Pollo Entero Grado A', stock_sistema: 50, stock_fisico: 48, diferencia: -2 },
      { producto_id: '2', producto_nombre: 'Cartón Huevos x30', stock_sistema: 18, stock_fisico: 20, diferencia: 2 },
      { producto_id: '3', producto_nombre: 'Pechuga Especial', stock_sistema: 15, stock_fisico: 15, diferencia: 0 },
      { producto_id: '4', producto_nombre: 'Muslos de Pollo', stock_sistema: 10, stock_fisico: 9, diferencia: -1 },
    ],
    estado: 'completado',
    fecha: '2026-04-10T10:00:00Z',
    created_at: '2026-04-10T10:00:00Z',
  },
  {
    id: 'conteo-002',
    numero: 'INV-0002',
    usuario_id: 'usr_002',
    usuario_nombre: 'Cajero 01',
    items: [
      { producto_id: '1', producto_nombre: 'Pollo Entero Grado A', stock_sistema: 48, stock_fisico: 48, diferencia: 0 },
      { producto_id: '2', producto_nombre: 'Cartón Huevos x30', stock_sistema: 20, stock_fisico: 19, diferencia: -1 },
      { producto_id: '3', producto_nombre: 'Pechuga Especial', stock_sistema: 15, stock_fisico: 15, diferencia: 0 },
    ],
    estado: 'completado',
    fecha: '2026-04-12T14:30:00Z',
    created_at: '2026-04-12T14:30:00Z',
  },
  {
    id: 'conteo-003',
    numero: 'INV-0003',
    usuario_id: 'usr_001',
    usuario_nombre: 'Admin User',
    items: [
      { producto_id: '1', producto_nombre: 'Pollo Entero Grado A', stock_sistema: 48, stock_fisico: 0, diferencia: 0 },
      { producto_id: '2', producto_nombre: 'Cartón Huevos x30', stock_sistema: 19, stock_fisico: 0, diferencia: 0 },
    ],
    estado: 'borrador',
    fecha: '2026-04-14T09:00:00Z',
    created_at: '2026-04-14T09:00:00Z',
  },
]
