export const RUTAS = {
  PUBLICO: {
    HOME: '/',
    CATALOGO: '/catalogo',
    REGISTRO: '/registro',
  },
  AUTH: {
    LOGIN: '/login',
    LOGIN_CLIENTE: '/mi-cuenta/login',
    CALLBACK: '/auth/callback',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    POS: '/admin/pos',
    VENTAS: '/admin/ventas',
    PRODUCTOS: '/admin/productos',
    COMPRAS: '/admin/compras',
    PROVEEDORES: '/admin/proveedores',
    CLIENTES: '/admin/clientes',
    COBRANZAS: '/admin/cobranzas',
    INVENTARIO: '/admin/inventario',
    INVENTARIO_CONTEO: '/admin/inventario/conteo',
    COMPROBANTES: '/admin/comprobantes',
    REPORTES: '/admin/reportes',
    CONFIGURACION: '/admin/configuracion',
    PERFIL: '/admin/perfil',
  },
  CLIENTE: {
    LOGIN: '/mi-cuenta/login',
    MI_CUENTA: '/mi-cuenta',
    VENTAS: '/mi-cuenta/ventas',
    COMPROBANTES: '/mi-cuenta/comprobantes',
    DEUDAS: '/mi-cuenta/deudas',
    EDITAR: '/mi-cuenta/editar',
  },
}
